/**
 * Demo backend for the PrimeQuant web GUI (dev only).
 *
 * Implements the contract documented in `src/lib/ws.ts` so the split-pane
 * terminal renders without the real quant daemon:
 *
 *   REST:
 *     GET /api/subagents            -> { subagents: SubagentEvent[] }
 *     GET /api/artifacts?kind=py    -> { artifacts: ArtifactEvent[] }
 *     GET /api/artifacts?kind=mq5   -> { artifacts: ArtifactEvent[] }
 *     GET /api/tearsheet/latest     -> { url: string }
 *     GET /artifacts/tearsheet.html -> demo tearsheet (iframe target)
 *
 *   WebSocket /ws (server -> client):
 *     chat / step / subagent / tearsheet / artifact events
 *
 *   WebSocket /ws (client -> server):
 *     { type: "chat", text: string }  -> triggers a simulated pipeline run
 *
 * Run: `npm run demo:backend` (web-ui workspace). Seeded with demo data and a
 * self-running pipeline cycle so the GUI is populated on connect.
 */
import { createServer } from "node:http";
import { WebSocketServer } from "ws";

const PORT = Number(process.env.PORT ?? 3001);

const SUBAGENTS = [
	{
		type: "subagent",
		id: "sub-1",
		name: "worker://eurusd-m5-scan",
		tier: "worker",
		status: "RUNNING",
		tokensPerMin: 12400,
		task: "param sweep: rsi(14) mean reversion on EURUSD M5",
	},
	{
		type: "subagent",
		id: "sub-2",
		name: "worker://gbpusd-h1-breakout",
		tier: "worker",
		status: "DONE",
		tokensPerMin: 9800,
		task: "Donchian breakout scan on GBPUSD H1",
	},
	{
		type: "subagent",
		id: "sub-3",
		name: "worker://audusd-regime",
		tier: "worker",
		status: "DONE",
		tokensPerMin: 8700,
		task: "volatility regime filter on AUDUSD H4",
	},
];

const STRATEGY_PY = `# eurusd_m5_mean_reversion.py
# Clean spec: no lookahead. Signals computed on closed bars; entries fill at
# the next bar open via the engine execution model (slippage + variable spread).
from primequant.strategy.base import StrategySpec
from primequant.backtest.engine import run_backtest
from primequant.validate.pipeline import run_validation_pipeline

spec = StrategySpec(
    symbol="EURUSD",
    timeframe="M5",
    asset_class="forex",
    risk_per_trade_pct=0.5,
    stop_loss_atr=2.0,
    take_profit_atr=3.0,
    lot_size_units=100_000,
)

def signals(df):
    rsi = df["close"].rolling(14).mean()
    return (df["close"] < rsi).astype(int)

result = run_backtest(spec, signals)
gate = run_validation_pipeline(spec, result)
print(gate.summary_json())
`;

const EXPERT_MQ5 = `//+------------------------------------------------------------------+
//| EURUSD_M5_MeanReversion_EA.mq5                                  |
//| Generated by primequant.report.tearsheet export                 |
//+------------------------------------------------------------------+
input double RiskPerTradePct = 0.5;
input int    AtrPeriod       = 14;
input double AtrStopMult     = 2.0;
input double AtrTargetMult   = 3.0;

double g_atr[];
int    g_atrHandle;

int OnInit() {
   g_atrHandle = iATR(_Symbol, PERIOD_M5, AtrPeriod);
   if (g_atrHandle == INVALID_HANDLE) return INIT_FAILED;
   ArraySetAsSeries(g_atr, true);
   return INIT_SUCCEEDED;
}

void OnTick() {
   if (CopyBuffer(g_atrHandle, 0, 0, 1, g_atr) < 1) return;
   if (PositionSelect(_Symbol)) return;          // one position at a time
   double atr = g_atr[0];
   double risk = AccountInfoDouble(ACCOUNT_BALANCE) * RiskPerTradePct / 100.0;
   double lots = NormalizeDouble(risk / (atr * AtrStopMult * _Point * 100000), 2);
   // Entry executes at the next tick after the signal bar closes:
   // strategy bar state is only consumed from closed bars (Close[1]).
   if (Close[1] < iMA(_Symbol, PERIOD_M5, 14, 0, MODE_SMA, PRICE_CLOSE, 1)) {
      double sl = Close[1] - atr * AtrStopMult * _Point;
      double tp = Close[1] + atr * AtrTargetMult * _Point;
      Trade.Buy(lots, _Symbol, 0.0, sl, tp, "mean-reversion");
   }
}
`;

const TEARSHEET_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>EURUSD M5 // tearsheet</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #0d1117; color: #c9d1d9;
         font: 12px/1.5 "JetBrains Mono", "Fira Code", ui-monospace, Menlo, monospace; }
  header { border-bottom: 1px solid #2d3748; padding: 10px 14px; }
  header h1 { margin: 0; font-size: 12px; letter-spacing: .12em; color: #58a6ff; }
  header p { margin: 2px 0 0; color: #8b949e; font-size: 11px; }
  section { border-bottom: 1px solid #2d3748; padding: 12px 14px; }
  h2 { margin: 0 0 8px; font-size: 10px; letter-spacing: .14em; color: #8b949e; }
  .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }
  .metric { border: 1px solid #2d3748; padding: 8px; }
  .metric b { display: block; font-size: 16px; color: #3fb950; }
  .metric span { font-size: 10px; color: #8b949e; text-transform: uppercase; letter-spacing: .1em; }
  .verdict { display: inline-block; border: 1px solid #3fb950; color: #3fb950;
             padding: 2px 8px; font-size: 11px; letter-spacing: .1em; }
  table { border-collapse: collapse; width: 100%; }
  td, th { border: 1px solid #2d3748; padding: 4px 6px; text-align: center; font-size: 11px; }
  th { color: #8b949e; font-weight: normal; }
  .dd-0 { background: #1f2937; } .dd-1 { background: #3b2f2f; }
  .dd-2 { background: #5c3330; } .dd-3 { background: #7d3a33; }
  .footer { color: #8b949e; font-size: 10px; padding: 8px 14px; }
</style>
</head>
<body>
<header>
  <h1>TEARSHEET // EURUSD M5 mean-reversion</h1>
  <p>period 2024-01-01 → 2025-12-31 · 412 trades · 100k standard units · next-open execution</p>
</header>

<section>
  <h2>PERFORMANCE</h2>
  <div class="grid">
    <div class="metric"><b>1.84</b><span>sharpe</span></div>
    <div class="metric"><b>2.12</b><span>sortino</span></div>
    <div class="metric"><b>1.95</b><span>calmar</span></div>
    <div class="metric"><b>4.8%</b><span>max dd</span></div>
    <div class="metric"><b>1.72</b><span>profit factor</span></div>
    <div class="metric"><b>54%</b><span>win rate</span></div>
    <div class="metric"><b>+$28.50</b><span>expectancy</span></div>
    <div class="metric"><b>+11.2%</b><span>net return</span></div>
  </div>
</section>

<section>
  <h2>EQUITY CURVE (100k starting capital)</h2>
  <svg viewBox="0 0 560 140" width="100%" height="140" preserveAspectRatio="none">
    <polyline fill="none" stroke="#58a6ff" stroke-width="1.5"
      points="0,112 20,109 40,111 60,105 80,107 100,100 120,103 140,95 160,98 180,90 200,93 220,85 240,88 260,80 280,84 300,76 320,80 340,72 360,76 380,66 400,70 420,62 440,66 460,56 480,60 500,52 520,56 540,44 560,48"/>
  </svg>
</section>

<section>
  <h2>DRAWDOWN HEATMAP (year × month, %)</h2>
  <table>
    <tr><th></th><th>J</th><th>F</th><th>M</th><th>A</th><th>M</th><th>J</th><th>J</th><th>A</th><th>S</th><th>O</th><th>N</th><th>D</th></tr>
    <tr><th>2024</th><td class="dd-1">.8</td><td class="dd-0">.2</td><td class="dd-2">1.6</td><td class="dd-1">.9</td><td class="dd-0">.1</td><td class="dd-3">2.8</td><td class="dd-1">.7</td><td class="dd-0">.0</td><td class="dd-2">1.4</td><td class="dd-1">.6</td><td class="dd-0">.3</td><td class="dd-1">.9</td></tr>
    <tr><th>2025</th><td class="dd-2">1.7</td><td class="dd-0">.4</td><td class="dd-1">.8</td><td class="dd-0">.2</td><td class="dd-3">3.1</td><td class="dd-1">.5</td><td class="dd-0">.1</td><td class="dd-1">.9</td><td class="dd-0">.3</td><td class="dd-2">1.2</td><td class="dd-0">.0</td><td class="dd-1">.6</td></tr>
  </table>
</section>

<section>
  <h2>OVERFIT GATE (CPCV + walk-forward)</h2>
  <p style="font-size:11px">deflated sharpe <b style="color:#3fb950">1.32</b> ·
     pbo <b style="color:#3fb950">0.11</b> ·
     oos degradation <b style="color:#d29922">22.4%</b></p>
  <span class="verdict">PASS — strategy is not an overfit artifact</span>
</section>

<div class="footer">generated by primequant.report.tearsheet · deterministic engine · demo data</div>
</body>
</html>
`;

const PY_ARTIFACTS = [
	{ type: "artifact", kind: "py", name: "eurusd_m5_mean_reversion.py", content: STRATEGY_PY },
];

const MQ5_ARTIFACTS = [
	{
		type: "artifact",
		kind: "mq5",
		name: "EURUSD_M5_MeanReversion_EA.mq5",
		content: EXPERT_MQ5,
	},
];

// A2 rooms demo: bounded in-memory room logs + watcher-style seeded posts.
const ROOMS = [
	{ id: "general", topic: "orchestrator chat" },
	{ id: "alerts", topic: "breaches and urgent watcher flags" },
	{ id: "risk-management", topic: "risk watcher output" },
	{ id: "research", topic: "research watcher and pipeline results" },
	{ id: "system-updates", topic: "bridge, daemon, and kernel notices" },
];

const roomLogs = new Map(ROOMS.map((room) => [room.id, []]));
let roomSeq = 0;

function postRoomMessage(room, from, text) {
	const message = {
		type: "room_message",
		room,
		id: `rm-${++roomSeq}`,
		from,
		text,
		ts: new Date().toISOString(),
	};
	const log = roomLogs.get(room) ?? [];
	log.push(message);
	if (log.length > 200) log.splice(0, log.length - 200);
	roomLogs.set(room, log);
	return message;
}

const SEEDED_ROOM_POSTS = [
	["risk-management", "watcher://risk", "@You daily-loss guard armed at 1% equity. Drawdown 2.4% — inside the 5% limit."],
	["research", "watcher://research", "triage complete: 2 of 5 queued ideas passed the validation gate. Top candidate: EURUSD M5 rsi(14) mean reversion (dsr 1.32, pbo 0.11)."],
	["system-updates", "bridge", "demo backend seeded — rooms, watchers, and pipeline fixtures live."],
];

let watcherTick = 0;

function sendJson(response, status, body) {
	response.writeHead(status, { "content-type": "application/json" });
	response.end(JSON.stringify(body));
}

function broadcast(clients, event) {
	const payload = JSON.stringify(event);
	for (const client of clients) {
		if (client.readyState === client.OPEN) client.send(payload);
	}
}

const server = createServer((request, response) => {
	const url = new URL(request.url ?? "/", `http://${request.headers.host ?? "localhost"}`);

	if (url.pathname === "/api/subagents" && request.method === "GET") {
		sendJson(response, 200, { subagents: SUBAGENTS });
		return;
	}
	if (url.pathname === "/api/artifacts" && request.method === "GET") {
		const kind = url.searchParams.get("kind");
		const artifacts = kind === "mq5" ? MQ5_ARTIFACTS : PY_ARTIFACTS;
		sendJson(response, 200, { artifacts });
		return;
	}
	if (url.pathname === "/api/tearsheet/latest" && request.method === "GET") {
		sendJson(response, 200, { url: "/artifacts/tearsheet.html" });
		return;
	}
	if (url.pathname === "/api/rooms" && request.method === "GET") {
		sendJson(response, 200, {
			rooms: ROOMS.map((room) => ({ ...room, messages: (roomLogs.get(room.id) ?? []).length })),
		});
		return;
	}
	const roomMatch = /^\/api\/rooms\/([a-z0-9-]+)\/messages$/.exec(url.pathname);
	if (roomMatch) {
		const roomId = roomMatch[1];
		if (!roomLogs.has(roomId)) {
			sendJson(response, 404, { error: "unknown room" });
			return;
		}
		if (request.method === "GET") {
			sendJson(response, 200, { room: roomId, messages: roomLogs.get(roomId) });
			return;
		}
		if (request.method === "POST") {
			let body = "";
			request.on("data", (chunk) => (body += chunk));
			request.on("end", () => {
				try {
					const parsed = JSON.parse(body);
					if (typeof parsed.from !== "string" || typeof parsed.text !== "string") {
						sendJson(response, 400, { error: "from and text are required" });
						return;
					}
					const message = postRoomMessage(roomId, parsed.from, parsed.text);
					broadcast(wss.clients, message);
					sendJson(response, 201, { message });
				} catch {
					sendJson(response, 400, { error: "invalid JSON body" });
				}
			});
			return;
		}
	}
	if (url.pathname === "/artifacts/tearsheet.html" && request.method === "GET") {
		response.writeHead(200, { "content-type": "text/html; charset=utf-8" });
		response.end(TEARSHEET_HTML);
		return;
	}
	sendJson(response, 404, { error: "not found" });
});

const wss = new WebSocketServer({ server, path: "/ws" });

let runCounter = 0;

/** Simulates one orchestrator pipeline run: AST check -> backtest -> CPCV gate. */
function runDemoPipeline(clients) {
	runCounter += 1;
	const runId = `run-${Date.now()}-${runCounter}`;
	const step = (name, status, detail) =>
		broadcast(clients, { type: "step", id: `${runId}-${name}`, name, status, detail });

	const queue = [
		[0, () => step("ast_check", "running")],
		[450, () => step("ast_check", "done", "no lookahead violations")],
		[650, () => broadcast(clients, { type: "chat", role: "assistant", text: "ast_check: passed — no future-indexing or leakage patterns in the strategy source." })],
		[950, () => step("backtest", "running")],
		[1400, () => step("backtest", "done", "412 trades · sharpe 1.84")],
		[1600, () => step("cpcv_gate", "running")],
		[2050, () => step("cpcv_gate", "done", "dsr 1.32 · pbo 0.11")],
		[2250, () => broadcast(clients, { type: "chat", role: "assistant", text: `Backtest complete. Summary card for ${runId}:\n\n\`\`\`json\n{\n  "status": "success",\n  "metrics": {\n    "sharpe_ratio": 1.84,\n    "sortino_ratio": 2.12,\n    "calmar_ratio": 1.95,\n    "max_drawdown_pct": 4.8,\n    "profit_factor": 1.72,\n    "win_rate": 0.54,\n    "expectancy_usd": 28.5,\n    "trades_count": 412\n  },\n  "validation_gate": { "passed": true, "deflated_sharpe": 1.32, "pbo": 0.11, "oos_degradation_pct": 22.4 }\n}\n\`\`\`\nEquity curve, drawdown heatmap and DSR card are in the tearsheet pane. Raw frames stay bound in the kernel.` })],
		[2350, () => broadcast(clients, { type: "subagent", id: "sub-1", name: "worker://eurusd-m5-scan", tier: "worker", status: "DONE", tokensPerMin: 12400, task: "param sweep: rsi(14) mean reversion on EURUSD M5" })],
		[2350, () => broadcast(clients, { type: "subagent", id: "sub-4", name: "worker://optimize-eurusd-m5", tier: "worker", status: "RUNNING", tokensPerMin: 15600, task: "optuna sweep: atr multiples" })],
		[2450, () => broadcast(clients, { type: "tearsheet", url: "/artifacts/tearsheet.html" })],
		[2550, () => broadcast(clients, { type: "artifact", kind: "py", name: "eurusd_m5_mean_reversion_v2.py", content: STRATEGY_PY })],
	];
	for (const [delay, fn] of queue) {
		setTimeout(fn, delay);
	}
}

wss.on("connection", (socket) => {
	socket.on("message", (data) => {
		let payload;
		try {
			payload = JSON.parse(String(data));
		} catch {
			return;
		}
		if (payload?.type === "chat" && typeof payload.text === "string") {
			runDemoPipeline([socket]);
		}
	});

	// Welcome, then kick off a self-running demo cycle so the GUI is alive
	// immediately after connect.
	broadcast([socket], { type: "rooms_state", rooms: ROOMS });
	for (const [room, from, text] of SEEDED_ROOM_POSTS) {
		const existing = (roomLogs.get(room) ?? []).find((message) => message.from === from && message.text === text);
		broadcast([socket], existing ?? postRoomMessage(room, from, text));
	}
	broadcast([socket], {
		type: "chat",
		role: "assistant",
		text: "orchestrator online. Demo backend seeded — I'll start a research run on EURUSD M5 (mean reversion) right away.",
	});
	setTimeout(() => runDemoPipeline([socket]), 700);

	// Watcher liveliness: a flow-watcher card every 45s into #alerts.
	const watcherTimer = setInterval(() => {
		watcherTick += 1;
		const z = (2.4 + Math.random() * 1.6).toFixed(1);
		const message = postRoomMessage(
			"alerts",
			"watcher://flow",
			`EURUSD M5 volume z-score ${z} (threshold 2.5) — ${Number(z) > 2.5 ? "anomaly flagged" : "within tolerance"} · tick ${watcherTick}`,
		);
		if (socket.readyState === socket.OPEN) broadcast([socket], message);
	}, 45000);
	socket.on("close", () => clearInterval(watcherTimer));
});

server.listen(PORT, () => {
	console.log(`[demo-backend] listening on http://localhost:${PORT} (ws: /ws)`);
});
